import pdfkit
import os
import pandas as pd
import tempfile

# ✅ Configure path to wkhtmltopdf
wkhtml_path = r"E:\UTA MSDS\wkhtmltopdf\bin\wkhtmltopdf.exe"
config = pdfkit.configuration(wkhtmltopdf=wkhtml_path)

def generate_risk_report(student_info: pd.DataFrame, prediction_label: str, shap_table: pd.DataFrame, output_path: str = "student_risk_report.pdf"):
    student_html = student_info.to_html(index=False, border=0)
    shap_html = shap_table.to_html(index=False, border=0)

    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; padding: 20px; }}
            h2 {{ color: #2c3e50; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ border: 1px solid #ccc; padding: 8px; text-align: left; }}
            th {{ background-color: #f4f4f4; }}
        </style>
    </head>
    <body>
        <h2>📋 Student Risk Prediction Report</h2>
        <p><strong>Prediction Status:</strong> {prediction_label}</p>

        <h3>🧍 Student Input Information</h3>
        {student_html}

        <h3>📌 Feature Contributions (SHAP)</h3>
        {shap_html}

        <hr>
        <p style="font-size: 12px;'>Generated by the Student Performance Dashboard © 2025</p>
    </body>
    </html>
    """

    tmp_html_path = os.path.join(tempfile.gettempdir(), "report.html")
    with open(tmp_html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    pdfkit.from_file(tmp_html_path, output_path, configuration=config)
    return output_path
